file       ::= object END | array END
object     ::= "{" member ("," member)* "}"
array      ::= "[" value ("," value)* "]"
member     ::= STRING ":" value
value      ::= object | array | literal
literal    ::= INT | FLOAT | STRING
