file       ::= object END | array END
object     ::= "{" "}" | "{" member ("," member)* "}"
array      ::= "[" "]" | "[" value ("," value)* "]"
member     ::= name ":" value
value      ::= object | array | literal
literal    ::= INT | FLOAT | STRING | BOOL
name       ::= STRING
